import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TRPCProvider from "./_trpc/Provider";
import { ThemeProvider } from "@/styles/ThemeProvider";
import { ThemeToggle } from "@/lib/ThemeToggle";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Todo App",
  description: "Generated by create Todo app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <TRPCProvider>
            <ThemeToggle />
            {children}
            <Toaster />
          </TRPCProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
